client_config_backend: file
client_config:
    client_id: 852749625849-p9f2m0dd9q2q3ukft7ugmkkn9oogb5c4.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/drive.install